apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pwned.fullname" . }}
  labels:
  {{- include "pwned.labels" . | nindent 4 }}
  namespace: myapp
spec:
  selector:
    matchLabels:
  {{- include "pwned.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
    {{- include "pwned.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pwned-config
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pwned-config
                  key: POSTGRES_DB_PORT
            - name: POSTGRES_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pwned-secret
                  key: POSTGRES_DB_USERNAME
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pwned-secret
                  key: POSTGRES_DB_PASSWORD
          ports:
            - containerPort: 8000