apiVersion: v1
kind: Service
metadata:
  name: {{ include "pwned.fullname" . }}
  labels:
  {{- include "pwned.labels" . | nindent 4 }}
  namespace: myapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
  {{- include "pwned.selectorLabels" . | nindent 4 }}